import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Playmate',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-between items-center h-16 sticky top-0 z-50 px-6 shadow-md bg-blue-900 text-white">
  {/* Logo section */}
  <div className="flex items-center gap-2">
    <div className="w-10 h-10 bg-white rounded-sm" />
    {/* Replace above with: <img src="/logo.png" alt="Logo" className="h-10" /> */}
    <span className="text-lg font-semibold">PlayMate</span>
  </div> 
  <Link href="/dashboard">
        <button className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition">
          Dashboard
        </button>
      </Link>
      <Link href="/uservenues">
        <button className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition">
          My Venues
        </button>
        </Link>

  {/* Auth section */}
  <div className="flex items-center gap-4">
    <SignedOut>
      <SignInButton />
      <SignUpButton />
    </SignedOut>
    <SignedIn>
      <UserButton />
    </SignedIn>
        </div>
        </header>

          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}